
/* 
    What is a Makefile?
    
        Makefiles are used to help decide which parts of a large program need to be recompiled. 
        In the vast majority of cases, C or C++ files are compiled. 
        Other languages typically have their own tools that serve a similar purpose as Make.
        Make can also be used beyond compilation too, when you need a series of instructions to run depending on what files have changed.

*/


/*
        Why Do We Use Makefiles? 
       

         Without Makefile (The Hard Way)
         
        Let's say you have a simple C program with 3 files: 
        
            gcc -c main.c          # Compile main.c
            gcc -c utils.c         # Compile utils.c  
            gcc -c math.c          # Compile math.c
            gcc main.o utils.o math.o -o myprogram   # Link everything
            
            
           Problems:
           
           You have to remember all these commands
           You have to type them every time
           If you change one file, you might recompile everything (slow!)
           Easy to make mistakes
           

           With Makefile (The Smart Way)
           bashmake                   # That's it! 🎉
            

*/